### ISSUE TITLE
daymn

### ISSUE THREAD

**Issue by Ezriral** [marsinator358/luajit-decompiler-v2#1]
i really hope you will finish this one, cause this is for sure something i cannot.

**Comment by marsinator358** [comment]
Well it's a work in progress which means that I haven't finished writing the core modules yet,
so it can't be used for anything right now except for debugging purposes
and inspecting bytecode (but there are better programs for that).

**Comment by marsinator358** [comment]
Check the readme for the TODOs but in summary the decompiler is now on par with the python one  
with additional support for gotos and stripped bytecode including upvalues.

I'm using the latest Microsoft Visual Studio but be aware that the repo is really only for reference,  
you should always download the latest executable from the release section as it may include  
some fixes I haven't commited yet.
