### ISSUE TITLE
Interest in a cross-platform port

### ISSUE THREAD

**Issue by toxamin** [marsinator358/luajit-decompiler-v2#10]
Do you have any interest in replacing the windows-specific code with cross platform c++?
I am willing to do the port myself and make a pull request if there is any interest.

**Comment by marsinator358** [comment]
Not really, the windows sdk is just too convenient. There is also no good replacement for MessageBoxA.

Also if you want to make changes then please be aware that the repo is really just for reference and currently out of date.  
It would probably be better if you create a fork instead.

**Comment by toxamin** [comment]
Thanks for the reply.
Any reason why you don't update the repository?

**Comment by marsinator358** [comment]
I was working on something, it's up to date now.

**Comment by kroggen** [comment]
In case the PR is not accepted, check [our fork](https://github.com/aergoio/luajit-decompiler-v2)

Working on Mac and Linux
