### ISSUE TITLE
Prototype read would exceed end of buffer

### ISSUE THREAD

**Issue by FlorianPaun** [marsinator358/luajit-decompiler-v2#11]
Hi, I've been trying to decompile some game files. Your compiler has worked for some of them, but not all. For most files I get this error:

```
Error running Bytecode::Prototype::get_next_byte
Source: bytecode\prototype.cpp:200

Prototype read would exceed end of buffer
```

I'm attaching one of the files that don't work and its decompiled version from an earlier version of the game (they might be the same in the end, i don't know, that's what I'm trying to find out). Could you have a look at it? If it's the file that is faulty, could you tell me what I'd have to change about it to make it work with your compiler? Thanks!

[test_files.zip](https://github.com/marsinator358/luajit-decompiler-v2/files/13368876/test_files.zip)

**Comment by marsinator358** [comment]
I'm using an older version of the FS22 luajit bytecode source myself and compared `TestAnimalCluster.lua` against your file.  
They're the same except the last 3 bytes. The file should end with `4E 00 00` but yours for some reason ends with `1B 18 E4`.

Is your file from the current version? Make sure that they are correctly extracted and decoded.

**Comment by FlorianPaun** [comment]
So I get it you've also struggled with the lack of script documentation from the developer? 

You're right, I changed the last 3 bytes of my decoded file manually and it worked. So there's something wrong with my decoded files, your decompiler works. I've tried the 2 decompilers below so far and both of them returned the same results. Woud you mind sharing the one you used? It would help immensely.

https://github.com/freedom-farmer-fs22/FS22_decompile/tree/main/helpers
https://github.com/chill1Penguin/l64decode/blob/master/l64decode.py

**Comment by marsinator358** [comment]
Oh yeah the modding sdk is a joke.  
I've tested the current version and it works fine for me. I'm using the l64decode.py from the bottom link  
in combination with [QuickBMS](http://quickbms.com) for dataS extraction.

**Comment by lightSoulDev** [comment]
Hi, I'm having the same issue with this file.
[output.zip](https://github.com/marsinator358/luajit-decompiler-v2/files/15126866/output.zip)
Are there any updates on this issue?

**Comment by marsinator358** [comment]
@lightSoulDev Did you comment on the wrong issue?  
Anyway, same problem as #8. Here is the decompiled file: [output.txt](https://github.com/marsinator358/luajit-decompiler-v2/files/15128204/output.txt)
