### ISSUE TITLE
Trailing whitespace after empty lines and returns

### ISSUE THREAD

**Issue by Aussiemon** [marsinator358/luajit-decompiler-v2#14]
Empty lines and returns contain trailing whitespace.

Diff comparison; green is luajit-decompiler-v2 output:
![image](https://github.com/marsinator358/luajit-decompiler-v2/assets/13663574/5f259f7d-4b37-4901-b5d5-5d438e6b10dc)

Potential fix for returns in `Lua::write_block`:
```
case Ast::AST_STATEMENT_RETURN:
	write_indent();
	if (i != block.size() - 1) write("do ");
	if (block[i]->assignment.expressions.size() || block[i]->assignment.multresReturn) {
		write("return ");
	} else {
		write("return");
	}
```
Whitespace in empty lines could be fixed by moving `write_indent();` into every case of `switch (block[i]->type)` in `Lua::write_block` instead of having it precede the switch, but maybe there's a better way.

**Comment by marsinator358** [comment]
The whitespace in the return statement is an oversight. I didn't care about the empty lines  
because they look the same in VS, but since VS doesn't indent I'll be changing them for consistency.
