### ISSUE TITLE
[Suggestion] Option to disable function definition syntactic sugar

### ISSUE THREAD

**Issue by Aussiemon** [marsinator358/luajit-decompiler-v2#16]
It would be useful to have a decompilation option for disabling function definition syntactic sugar:

```
function <table>:<name>(...)
```
would become
```
<table>.<name> = function (self, ...)
```

Could be accomplished with this snippet in Lua::write_block:
```
if (isFunctionDefinition) {
	if (!previousLineIsEmpty) {
		write(NEW_LINE);
		write_indent();
	}

	if (block[i]->assignment.variables.back().type == Ast::AST_VARIABLE_TABLE_INDEX
		&& block[i]->assignment.expressions.back()->function->parameterNames.size()
		&& block[i]->assignment.expressions.back()->function->parameterNames.front() == "self") {
		write_variable(*block[i]->assignment.variables.back().table->variable, false);
		write(".", block[i]->assignment.variables.back().tableIndex->constant->string);
		write(" = function ");
		write_function_definition(*block[i]->assignment.expressions.back()->function, false);
	} else {
		write_variable(block[i]->assignment.variables.back(), false);
		write(" = function ");
		write_function_definition(*block[i]->assignment.expressions.back()->function, false);
	}
```

**Comment by marsinator358** [comment]
When would this be useful, if I may ask?  
This would also cause local functions to require an additional forward declaration if the local is an upvalue.

**Comment by Aussiemon** [comment]
> When would this be useful, if I may ask? This would also cause local functions to require an additional forward declaration if the local is an upvalue.

Self parameter:
1. Clearer to a casual reader than the colon
2. Our mod framework uses hooks that pass the hooked function's parameters to a new function, e.g. `mod:hook(ConstantElementChat, "using_input", function (func, self, param1, param2, param3, ...)`. This is easier to write when you can copy the parameters directly from the definition.
3. Search for a function definition by "table.name" and the results won't include function calls that use "table:name".

Sugarfree function definitions are mostly preference, and I don't think we need them for local function definitions (LJD doesn't either). Some reasons in support:
1. Clearer function table membership at a glance:
```
tablename.f0 = function (self) end
tablename.f1 = function (self) end
tablename.f2 = function (self) end

f3 = function (self) end
f4 = function (self) end

vs

function tablename:f0() end
function tablename:f1() end
function tablename:f2() end

function f3() end
function f4() end
```
2. Cleaner with mixed assignments:
```
local tablename = {}

tablename.f0 = function (self) end
tablename.f1 = 1
tablename.f2 = function (self) end

f3 = 1
f4 = function (self) end

vs

function tablename:f0() end
tablename.f1 = 1
function tablename:f2() end

f3 = 1
function f4() end
```

**Comment by marsinator358** [comment]
I think this might be a bit too specific of a use case to include in the project.  
Maybe include the changes in your fork instead?
