### ISSUE TITLE
Inverted comparisons and flipped operands

### ISSUE THREAD

**Issue by Aussiemon** [marsinator358/luajit-decompiler-v2#19]
The snippet
```
b = (y or x) and z or x
```
becomes
```
b = not (not y and not x) and z or x
```

And the snippet
```
function a()
	local x = y()
	
	if z <= x then
		b = 1
	end
end
```
becomes
```
function a()
	local x = y()
	
	if x >= z then
		b = 1
	end
end
```
The latter will also flip operands in the `>`,`<`, and `<=` cases.

Both are still logically equivalent.

**Comment by marsinator358** [comment]
The first case will be improved in the future, but the second one is impossible because the order of the operands  
is lost if at least one of them is a local. I just prefer to keep the local on the left.

**Comment by Aussiemon** [comment]
> The first case will be improved in the future, but the second one is impossible because the order of the operands is lost if at least one of them is a local. I just prefer to keep the local on the left.

Interesting - LJD flips operands so that the comparison is always `<` or `<=`, but it does this regardless of whether one of the operands is a local or not; so less accurate overall.

**Comment by marsinator358** [comment]
The first case should now be resolved with the latest release.
