### ISSUE TITLE
UTF-8 string support

### ISSUE THREAD

**Issue by Timo654** [marsinator358/luajit-decompiler-v2#2]
It would be great to have UTF-8 support for strings. Right now I get this in some of the files I've tried the tool on:
![image](https://github.com/marsinator358/luajit-decompiler-v2/assets/41972888/b2e597a1-e5dd-41dd-ad8f-2c8b642f3b26)

**Comment by marsinator358** [comment]
I've updated the executable, please let me know if it solves your problem or not.

**Comment by Timo654** [comment]
It works now, thanks! 
![image](https://github.com/marsinator358/luajit-decompiler-v2/assets/41972888/eafc0da2-958e-43a2-8d58-33feba5fe065)
