### ISSUE TITLE
Commandline mode doesn't create output path with -o parameter

### ISSUE THREAD

**Issue by Aussiemon** [marsinator358/luajit-decompiler-v2#20]
Running LuaJIT Decompiler v2 through Powershell with this command:
```
Start-Process -NoNewWindow -FilePath $decompiler_path -ArgumentList "`"$script_directory`" -o `"$output_path`" -e lua -s" -Wait
```

Paths are:
```
$decompiler_path="<truncated>\luajit-decompiler-v2.exe"
$script_directory="<truncated>\extracted_testset\vermintide2\scripts"
$output_path="<truncated>\decompiled_testset\vermintide2\scripts"
```

Example output:
```
LuaJIT Decompiler v2
Compiled on Nov 23 2023
Failed to open output path: <truncated>\decompiled_testset\vermintide2\scripts
```

No directories exist in `decompiled_testset`, so it seems the application fails to create the intermediate directories required to create the output files in the `scripts` directory.

**Comment by Aussiemon** [comment]
The easy workaround is to create the directories in Powershell, but it seems like the application is intended to create the intermediate paths, so I thought I'd report it.

**Comment by marsinator358** [comment]
That's intended, the custom output path needs to exist.  
The program only replicates the directory structure from the input path when in recursive mode.
