### ISSUE TITLE
Error running Bytecode get net byte

### ISSUE THREAD

**Issue by valtoo16** [marsinator358/luajit-decompiler-v2#21]
Hello !

When i execut the program with this luaJIt, i have this error 

[myfile (6).dmp](https://github.com/marsinator358/luajit-decompiler-v2/files/13537529/myfile.6.dmp)

![Capture](https://github.com/marsinator358/luajit-decompiler-v2/assets/15092440/4f898765-288f-44c8-bcac-c0b810f5902b)

thank you in advance

**Comment by valtoo16** [comment]
not possible to see where it is buggy?

**Comment by marsinator358** [comment]
There are strings near the end of the file that are overlapping with instructions that aren't supposed to be there.  
The file seems also too short and is missing the main prototype (function).
