### ISSUE TITLE
Minimize diffs of tables by using trailing comma

### ISSUE THREAD

**Issue by Aussiemon** [marsinator358/luajit-decompiler-v2#22]
Recently requested for LJD, although it's an enhancement I've been considering for a while: https://github.com/Aussiemon/ljd/issues/14

Lua syntactic sugar allows trailing commas after the last element in a table definition. Always adding this comma means diffs are smaller when new elements are added to the table.
```
mytable = {
    1,
    2,
}
```

**Comment by marsinator358** [comment]
I'd like to keep the current default output as it is, but would consider adding an CLI option  
that would also contain other formatting changes to make diffing easier, like #9.

Do you have ideas for additional changes?

**Comment by Aussiemon** [comment]
> I'd like to keep the current default output as it is, but would consider adding an CLI option that would also contain other formatting changes to make diffing easier, like #9.
> 
> Do you have ideas for additional changes?

You could alphabetize keys in table definitions. The original order is lost when the file compiles, and recompiling seems to re-order the list in a non-deterministic way (at least with my test tables). Alphabetizing the keys would minimize diffs and produce a cleaner output:

![image](https://github.com/marsinator358/luajit-decompiler-v2/assets/13663574/ad6ed953-893f-4e9b-b580-c604a2b988fc)

**Comment by marsinator358** [comment]
I can sort the keys, but it would have to be by byte value as unicode sorting is to complex.

> The original order is lost when the file compiles

Only the order of constant fields is lost, the order of non constants is reflected in the bytecode instruction order.

**Comment by Aussiemon** [comment]
> Only the order of constant fields is lost, the order of non constants is reflected in the bytecode instruction order.

That explains why it seemed inconsistent. Neat!

**Comment by Aussiemon** [comment]
> > Only the order of constant fields is lost, the order of non constants is reflected in the bytecode instruction order.
> 
> That explains why it seemed inconsistent. Neat!

Ah I misunderstood at first read. Yeah, I was referring to sorting the constant fields. On that note, anything that makes the output deterministic for any compilation of the same code would help with cleaner diffs. I can't think of any other places like that right now though.

I'm also not sure what the sort behavior should be for any table that mixes constants and non-constants. The decompiler (or the bytecode, I haven't checked) places all the non-constants at the end of the table and preserves their bytecode order from that point forward. Perhaps the decompiler should only sort the constant keys and continue to leave the non-constant order intact. That seems intuitive at least.
