### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by vanluat** [marsinator358/luajit-decompiler-v2#25]
[tmp.txt](https://github.com/marsinator358/luajit-decompiler-v2/files/13883277/tmp.txt)
![image](https://github.com/marsinator358/luajit-decompiler-v2/assets/10861831/e3bc8dc2-83f2-47f4-a1d8-beaf7f39d6d6)
hope u fix it.
thank you so much!

**Comment by marsinator358** [comment]
Thanks for reporting! This bug is a bit complex and the fix will be part of a future rewrite.

Here is the decompiled file: [decompiled.txt](https://github.com/marsinator358/luajit-decompiler-v2/files/13884231/decompiled.txt)

**Comment by vanluat** [comment]
thank you so much! @marsinator358
