### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ImNotSoftik** [marsinator358/luajit-decompiler-v2#26]
![image](https://github.com/marsinator358/luajit-decompiler-v2/assets/78680226/c2c9c9d7-da7c-46ef-a1ce-2f731e68c779)

**Comment by marsinator358** [comment]
This error is probably caused by randomized instructions in the bytecode  
which is a common thing for files that are protected against decompilation.  
You will need to find a tool that removes these instructions first.

**Comment by ImNotSoftik** [comment]
> first

Where can I find such a tool?

**Comment by marsinator358** [comment]
> Where can I find such a tool?

I'm not aware of any such tools, but you could ask [in this thread on blast.hk](https://www.blast.hk/threads/18162/) if they can    
decompile the file for you as they seem to be able to get around these protections.
