### ISSUE TITLE
Read unexpectedly reached end of file - Bytecode::buffer_next_block()

### ISSUE THREAD

**Issue by Ramen2X** [marsinator358/luajit-decompiler-v2#27]
Hi there - I'm working on a small reversing project and the included Lua files are giving me trouble. The header magic and the strings in the file look okay on the surface, but I have very limited knowledge of Lua bytecode so I'm unable to debug it further myself.

Attached is a file that can replicate the issue.
[lua.txt](https://github.com/marsinator358/luajit-decompiler-v2/files/13924136/lua.txt)

**Comment by marsinator358** [comment]
The file looks good expect at the end, it's 4 bytes too long. While deleting them  
will work it could also be a sign that the file is corrupted and is perhaps missing data.  
Please make sure that you dumped/extracted the file correctly.

**Comment by Ramen2X** [comment]
Ah, I see. I didn't catch that before. Seems like this was an issue higher up in the toolchain I was working with. I'm getting great output now. Sorry to bother you; thanks for the help!
