### ISSUE TITLE
unsupported instruction

### ISSUE THREAD

**Issue by Indigogou** [marsinator358/luajit-decompiler-v2#29]
Hi sir, i found bug in the file, unsupport instruction
[tmp2.txt](https://github.com/marsinator358/luajit-decompiler-v2/files/14041930/tmp2.txt)
![image](https://github.com/marsinator358/luajit-decompiler-v2/assets/157632837/f9f217a7-eda6-4b0b-9a94-fe388089c856)

**Comment by marsinator358** [comment]
Your file is protected against decompilation, you will need  
to find a tool that can restore the bytecode (see #26).

**Comment by Indigogou** [comment]
how can i protect file like this sir

**Comment by marsinator358** [comment]
Do you mean how to unprotect? I don't know, but you could ask [in this thread on blast.hk](https://www.blast.hk/threads/18162/)  
if they can decompile the file for you as they know how to get around the protection.

**Comment by Indigogou** [comment]
thank you
