### ISSUE TITLE
Problem with unsigned numbers

### ISSUE THREAD

**Issue by Gaztoof** [marsinator358/luajit-decompiler-v2#30]
Hey, you've done amazing work with this project!

However I came across a problem: unsigned numbers are not properly handled by the decompiler...
So sometimes an instruction will perform arithmetic on an unsigned number, which can be a byte of value 241 value for instance(it's unsigned), but when I run the decompiled code, the 241 value is rather interpreted as -14 which causes everything to break.

I can provide example files and the exact line where it happens if required? Just lmk !

**Comment by marsinator358** [comment]
> So sometimes an instruction will perform arithmetic on an unsigned number

Are you sure? Lua doesn't have unsigned numbers, only doubles  
(which sometimes get stored as signed integers in the bytecode).

> I can provide example files and the exact line where it happens if required?

Yes please do.

**Comment by Gaztoof** [comment]
[sv_init_x64.zip](https://github.com/marsinator358/luajit-decompiler-v2/files/14234431/sv_init_x64.zip)

When I execute the LUAC file using luajit directly var_1_71 has a positive value, but for some reason in the decompiled lua file at around line 219 var_1_71.

**Comment by marsinator358** [comment]
Are you trying to manually deobfuscate the file? If so I can't really help you with that.  
Did you check the value of var_1_71 in the unmodified file? What's the value of var_1_70?

If pcall fails then var_1_70 is false and var_1_71 is an error code instead, maybe that's the cause of your problem.

**Comment by Gaztoof** [comment]
I am not trying to de-obfuscate that file but rather have an executable LUA version of the LUAC file which I would then be able to edit as I wish.
The luac script is supposed to be ran on the game Garry's mod which uses LuaJIT, and so as I said loading the bytecode file works but not the decompiled one :/ That's why I think there must be a problem somewhere with the decompiler

**Comment by marsinator358** [comment]
Does the unmodifed decompiled file not work too? Anyway, I can't help you, I'm not even sure  
if this decompiler is compatible as Garry's Mod seems to have made some changes to LuaJIT.

**Comment by Gaztoof** [comment]
The direct output from your decompiler doesn't work, i've only lightly modified the file so that it's easier for you to understand it. GMOD's changes are minor and they're just syntax changes but nothing in the language's functioning (for example, it allows != to be used instead of ~=).

And the luac file is fine when loaded with luaL_loadbuffer and not gmod's modified luajit api or whatever =/

**Comment by marsinator358** [comment]
I've messed around with the file a little and it seems like that the behavior  
of the obfuscated code is somehow influenced by the file itself ???

For example, I've managed to change the printed value by simply inserting comments in the code.  
Not only that, but compiling the file will also result in a different value (it's positive too!).  

So please try to run the decompiled file again but compile it with LuaJIT first.

**Comment by toxamin** [comment]
this is a line check, minify the file and the output is as expected: 1

**Comment by toxamin** [comment]
i have deobfuscated this file for you :)
[sv_init_x64_minified-d.zip](https://github.com/marsinator358/luajit-decompiler-v2/files/14279219/sv_init_x64_minified-d.zip)

**Comment by Gaztoof** [comment]
Yea as toxamin said minifying it fixes the weird behavior!


Also, toxamin is there any chance I could contact you privately ?

**Comment by toxamin** [comment]
add me on discord @toxamin
