### ISSUE TITLE
Skip invalid/unsupported instructions

### ISSUE THREAD

**Issue by 0x0101x0** [marsinator358/luajit-decompiler-v2#35]
Hi, first of all, thanks for this project, it's very useful!

I get the following error , when I try to decompile a file:
"Prototype has invalid instruction (0xE0)"

How could skip invalid/unsupported instructions and print code using known instructions only?
Thanks!

[test.luac.zip](https://github.com/marsinator358/luajit-decompiler-v2/files/14719919/test.luac.zip)

**Comment by marsinator358** [comment]
Your file seems to be encrypted or used in conjunction with a modifed version of luajit.  
In either case I can't help you as this decompiler is only for unmodified bytecode.

> How could skip invalid/unsupported instructions and print code using known instructions only?

That would only work if you remove all instructions/functions that contain invalid data  
and checking for that is too much work and outside the scope of the project.

You may be able to find a tool that can remove some anti-decompilation protections though.
