### ISSUE TITLE
Failed to close slot scopes

### ISSUE THREAD

**Issue by 0x0101x0** [marsinator358/luajit-decompiler-v2#36]
Hi, 
I'm trying to decompile this lua file: https://fromsmash.com/NU_8IYL_j--dt

But I get the following error: 
"Failed to close slot scopes"

How could I solve it?

Thanks! 

Ps: could you share your contact so I won't open issue here every time?

**Comment by marsinator358** [comment]
There was a flag in the bytecode that wasn't set for some reason, this one works: [a0.txt](https://github.com/marsinator358/luajit-decompiler-v2/files/14733667/a0.txt)  

> could you share your contact so I won't open issue here every time?

I'd prefer if you open an issue as makes it easier for me to keep track of bugs.

**Comment by 0x0101x0** [comment]
Hi, 
I've tried to decompile the file that you've sent but it's not decompiling, It gives unknown exception.

Maybe you've uploaded the wrong file?

Thanks a lot for your help

**Comment by marsinator358** [comment]
I was using a newer decompiler (the old one had a bug), please download the new version.
