### ISSUE TITLE
Error : Ast::build_if_statements

### ISSUE THREAD

**Issue by vanluat** [marsinator358/luajit-decompiler-v2#4]
[FaithSkillVesselWidget.zip](https://github.com/marsinator358/luajit-decompiler-v2/files/13065450/FaithSkillVesselWidget.zip)
![image](https://github.com/marsinator358/luajit-decompiler-v2/assets/10861831/0b63c29c-daf8-4e2d-9971-5eaee5bad62a)

Hope you fix it !

Thank you

**Comment by marsinator358** [comment]
Fixed, thanks!
