### ISSUE TITLE
build / compile-instructions or system missing

### ISSUE THREAD

**Issue by emdete** [marsinator358/luajit-decompiler-v2#41]
how is this tool build / compiled? i cant find a makefile or such or any instructions how to build the tool.

**Comment by marsinator358** [comment]
Install Visual Studio, open it, hit "_Continue without code_" and goto `File->New->Project From Existing Code`.  
Select the folder with the source code and choose console application as the project type.  
Enable [C++20](https://learn.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=msvc-170#to-set-this-compiler-option-in-the-visual-studio-development-environment) and set the [default char to unsigned](https://learn.microsoft.com/en-us/cpp/build/reference/j-default-char-type-is-unsigned?view=msvc-170#to-set-this-compiler-option-in-the-visual-studio-development-environment), then simply build/run it.
