### ISSUE TITLE
Problems with decompiling juajit 2.1.1 (x86)

### ISSUE THREAD

**Issue by lightSoulDev** [marsinator358/luajit-decompiler-v2#43]
Invalid bytecode version (0xA1).

Is there a way to add support for this version? Here is the example script and the compiler that was used.
[script&compiler.zip](https://github.com/marsinator358/luajit-decompiler-v2/files/15474885/script.compiler.zip)

**Comment by marsinator358** [comment]
It's just version 2 bytecode but renamed so simply open the file with any hex editor  
and change the fourth byte from `A1` to `02`.
