### ISSUE TITLE
Getting Invalid Byte Code Version 

### ISSUE THREAD

**Issue by IamSanjid** [marsinator358/luajit-decompiler-v2#46]
[random.zip](https://github.com/user-attachments/files/16872992/random.zip)
![image](https://github.com/user-attachments/assets/a146cf8b-12d4-4982-889a-0e7a125c72d9)
The signature looks like a LuaJit bytecode files, but when I try to decompile I get Invalid ByteCode version

**Comment by marsinator358** [comment]
The file is encrypted

**Comment by IamSanjid** [comment]
> The file is encrypted

Ah thanks time to reverse engineer the shit just needed some confirmation the `\x1BLZ` header threw me off
