### ISSUE TITLE
question

### ISSUE THREAD

**Issue by majunjunquan** [marsinator358/luajit-decompiler-v2#47]
![QQ截图20240908205505](https://github.com/user-attachments/assets/341f81e4-5709-442d-80ae-96d3d7c19be4)
Hi, Unable to parse

**Comment by marsinator358** [comment]
Please upload the file so I can have a look.

**Comment by majunjunquan** [comment]
[111.zip](https://github.com/user-attachments/files/16932526/111.zip)
Thank you for your reply

**Comment by marsinator358** [comment]
This looks like a custom LuaJIT version, or at least I couldn't reproduce the bytecode with the standard compiler.

Are you using your own fork of this decompiler? If so, you can fix the error by replacing this line:
https://github.com/marsinator358/luajit-decompiler-v2/blob/b89b76b893e9b4c3231a5a917f47bfa8bfaccd7d/ast/ast.cpp#L352
with this:
``` cpp
if (function.block[i]->instruction.target < function.block[i]->instruction.id) {
	function.remove_jump(function.block[i]->instruction.id, function.block[i]->instruction.target);
	function.block[i]->instruction.type = Bytecode::BC_OP_ITERL;
	continue;
}
```

**Comment by majunjunquan** [comment]
Few files can be parsed, target version LuaJIT-2.0.5. Your tool is excellent and currently has the strongest parsing. Can you help me try to fix it

**Comment by marsinator358** [comment]
So the error happens because the LOOP and the ITERL instructions are swapped.  
You can use this modified exe to decompile the files: [luajit-decompiler-v2.zip](https://github.com/user-attachments/files/17005540/luajit-decompiler-v2.zip)

However please note that you need to change the chinese file/path names to be able to decompile the files.

**Comment by majunjunquan** [comment]
Thank you very much. You have strong technical skills and are enthusiastic, which is great
