### ISSUE TITLE
Failed to decompile 1 file.

### ISSUE THREAD

**Issue by aqing666** [marsinator358/luajit-decompiler-v2#48]
LuaJIT Decompiler v2
Compiled on Apr 15 2024
No input path specified!
Please select a valid LuaJIT bytecode file.
--------------------
Input file: C:\Users\Administrator\Desktop\lua\list.lua
Reading bytecode...
File skipped.
--------------------
Failed to decompile 1 file.
Done!
Press enter to exit.
[lua.zip](https://github.com/user-attachments/files/17166863/lua.zip)

**Comment by aqing666** [comment]
2.1.0_beta3_64

**Comment by marsinator358** [comment]
The files are corrupted. If you open them with a hex editor you will find many `EF BF BD` sequences.  
These are [UTF-8 replacement chars](https://www.cogsci.ed.ac.uk/%7Erichard/utf-8.cgi?input=ef+bf+bd&mode=bytes). Check that you're dumping/extracting the files correctly as raw binary and not as text.
