### ISSUE TITLE
Failed to close slot scopes

### ISSUE THREAD

**Issue by IamSanjid** [marsinator358/luajit-decompiler-v2#49]
Looks like duplicate of https://github.com/marsinator358/luajit-decompiler-v2/issues/36 but I am not sure what's the next step? Uploaded the file.
[lazy_require.zip](https://github.com/user-attachments/files/17213337/lazy_require.zip)

**Comment by marsinator358** [comment]
Not a duplicate as this error can have different causes.

Seems like the file has been compiled with a custom LuaJIT version because some of the instructions are swapped.  
I've managed to decompile it but the output is probably incorrect: [lazy_require.txt](https://github.com/user-attachments/files/17214391/lazy_require.txt)

I may be able to figure out the correct order if you provide more files or, if possible, the compiler that has been used.

**Comment by IamSanjid** [comment]
> I may be able to figure out the correct instruction order if you provide more files
here are some files:
  functools.lua -> Unknown Exception
  lz4.lua -> Unknown Exception
  language.lua -> Works (just in case you want to pattern match)
  rest of the files gives same error as the issue.
  
[util.zip](https://github.com/user-attachments/files/17228128/util.zip)

>  if possible, the compiler that has been used.
I have access to the android "runtime" lib which executes those luajit values, I can provide you that if you want, it should pretty straight forward if you use Ghidra or IDA, I just don't know about LuaJit and what am I suppose to look for so I am not useful :"). Thanks btw.

**Comment by marsinator358** [comment]
I've decompiled the other files but the output is still incorrect, they're just too small to make a good guess.
[decompiled.zip](https://github.com/user-attachments/files/17228616/decompiled.zip)


> I have access to the android "runtime" lib which executes those luajit bytecodes, I can provide you that if you want, it should pretty straight forward if you use Ghidra or IDA(not encrypted/obfuscated)

I don't use those tools so I won't be of much help, but let me know if you find a way to compile a lua string/file and output the bytecode.

**Comment by IamSanjid** [comment]
> I've decompiled the other files but the output is still incorrect, they're just too small to make a good guess. [decompiled.zip](https://github.com/user-attachments/files/17228616/decompiled.zip)

Here's the all the files which might've used the "custom" compiler I have accessed to:
[OkamiDatax32.zip](https://github.com/user-attachments/files/17228846/OkamiDatax32.zip)

Meanwhile I will try to see
> let me know if you find a way to compile a lua string/file and output the bytecode.

**Comment by marsinator358** [comment]
Seems like there are only 4 instructions that haven been swapped with each other  
but I can only verify this if you find a way to run your own lua code inside the app.

Anyway, here is a modified version of the decompiler that works with all files: [luajit-decompiler-v2.zip](https://github.com/user-attachments/files/17232154/luajit-decompiler-v2.zip)

**Comment by IamSanjid** [comment]
> Seems like there are only 4 instructions that haven been swapped with each other but I can only verify this if you find a way to run your own lua code inside the app.

Running our own compiled lua bytecodes? I think can do that, may be try to edit the `src/main.lua` from the previous `OkamiDatax32.zip` file I provided and compile it to the "swapped" instruction version? If you decide to continue let me know.

**Comment by marsinator358** [comment]
Try to run this file and if it works it will hopefully create a bytecode file called `instructions.ljbc`: [main.zip](https://github.com/user-attachments/files/17237741/main.zip)
