### ISSUE TITLE
Prototype has unsupported instruction

### ISSUE THREAD

**Issue by Velocet** [marsinator358/luajit-decompiler-v2#5]
Hi there and thanks for this awesome decompiler which worked great so far! 👍🏻 

With your newest version it seems it's not possible to decompile anything. I attached one of my files to (hopefully) help with debugging. If i can "help" any further then please let me know!

[internald.zip](https://github.com/marsinator358/luajit-decompiler-v2/files/13069253/internald.zip)

![image](https://github.com/marsinator358/luajit-decompiler-v2/assets/3201611/ac084f9c-0cf8-4413-a76d-0088860df6ac)

**Comment by marsinator358** [comment]
Oops I've made a typo which broke version 1 bytecode. Fixed, thanks!
