### ISSUE TITLE
How use this decompiler?

### ISSUE THREAD

**Issue by Sharpyku** [marsinator358/luajit-decompiler-v2#50]
Someone can explain me please step by step how can i use this? because i didnt understand anything..

**Comment by marsinator358** [comment]
1. Download  `luajit-decompiler-v2.exe` from [the release section](https://github.com/marsinator358/luajit-decompiler-v2/releases)
2. Drag and drop a LuaJIT bytecode file onto the exe or double-click the exe to select a file
3. You can find the decompiled `lua` file in the newly created `output` folder found in the same directory

**Comment by Sharpyku** [comment]
![Screenshot 2024-10-14 220808](https://github.com/user-attachments/assets/f480e197-3157-4eef-bac1-210ebd8883e9)
I get this error...

**Comment by marsinator358** [comment]
The file is either not a LuaJIT bytecode file or encrypted by the application that you are trying to decompile.
