### ISSUE TITLE
Compile source code

### ISSUE THREAD

**Issue by qingguonanshan** [marsinator358/luajit-decompiler-v2#51]
What do you use to compile the source code, I have an error when compiling, c++20

**Comment by marsinator358** [comment]
You need Visual Studio (MSVC) to compile this project. Don't forget to set the [default char to unsigned](https://learn.microsoft.com/en-us/cpp/build/reference/j-default-char-type-is-unsigned?view=msvc-170#to-set-this-compiler-option-in-the-visual-studio-development-environment).

**Comment by qingguonanshan** [comment]
ok，thanks you！
