### ISSUE TITLE
generated by LuaJIT 2.1 cannot be decompiled, and the error message is displayed.

### ISSUE THREAD

**Issue by fairyqb** [marsinator358/luajit-decompiler-v2#52]
The demo1-version-LuaJIT 2.1.0-beta3.ljbc generated by LuaJIT 2.1.0-beta3 can be decompiled.

However, the demo2-version-LuaJIT 2.1.ljbc generated by LuaJIT 2.1 cannot be decompiled, and the error message is displayed.

![pic](https://github.com/user-attachments/assets/e53b4f41-3862-4f95-80bc-965f403cad99)

[demo1-version-LuaJIT 2.1.0-beta3.ljbc.txt](https://github.com/user-attachments/files/17568093/demo1-version-LuaJIT.2.1.0-beta3.ljbc.txt)

[demo2-version-LuaJIT 2.1.0.ljbc.txt](https://github.com/user-attachments/files/17568096/demo2-version-LuaJIT.2.1.0.ljbc.txt)

**Comment by fairyqb** [comment]
@marsinator358  @Aussiemon help...

**Comment by marsinator358** [comment]
The demo2 file has been compiled by a modified version of LuaJIT 2.1 which is not supported by this decompiler.  
However, I may be able to help you if you can provide the compiler that has been used.

**Comment by marsinator358** [comment]
Here is a version of the decompiler that works with the modified LuaJIT 2.1 bytecode: [luajit-decompiler-v2.zip](https://github.com/user-attachments/files/17579979/luajit-decompiler-v2.zip)

**Comment by fairyqb** [comment]
It's works，thank you very much

**Comment by JarosLucky** [comment]
> Here is a version of the decompiler that works with the modified LuaJIT 2.1 bytecode: [luajit-decompiler-v2.zip](https://github.com/user-attachments/files/17579979/luajit-decompiler-v2.zip)
Can you reupload?
