### ISSUE TITLE
can you please help ? 

### ISSUE THREAD

**Issue by Samthapa76** [marsinator358/luajit-decompiler-v2#53]
when ever i decrypt any luac script if it is Russian or Spanish language text look  "-\xD1\xE8\xF1\xF2\xE5\xEC\xFB-" this is what it shows and believe me translating is pain in butt with this text please try to make it possible to ignore "text to convert weird language please"  let it be as it is i think its not hard for you just that and thanks for luajit-decompiler-v2 ty for wonderful tools

**Comment by Samthapa76** [comment]
if any chance you wanna take a look if no time no problem 
and btw this 2 files here this not possible to decrypt maybe you can do something
https://www.mediafire.com/file/eltgx87wx6awvb5/Color_Vehiculo.7z/file
https://www.mediafire.com/file/kxmu29cj1zmjgjo/Killstat.7z/file

**Comment by marsinator358** [comment]
> please try to make it possible to ignore

The hex escape sequences are there because of the default UTF-8 encoding and there is already  
an option that disables this. Simply run the decompiler in a command prompt with the `-u` option.
