### ISSUE TITLE
Can't decompile

### ISSUE THREAD

**Issue by huzpsb** [marsinator358/luajit-decompiler-v2#55]
[game.zip](https://github.com/user-attachments/files/18269856/game.zip)

**Comment by marsinator358** [comment]
The file has been compiled by a heavily modified version of LuaJIT which is not supported by this decompiler.  
I may be able to help you if you can provide the compiler that has been used.

**Comment by huzpsb** [comment]
> The file has been compiled by a heavily modified version of LuaJIT which is not supported by this decompiler. I may be able to help you if you can provide the compiler that has been used.

Thank you for confirming that! I think i'll give up decompiling this, since I have no access to the compiler (I have the runtime only and that runtime somehow doesn't support uncompiled code)...  
Seems if I want to somehow modify this lua and make it run in an unmodified runtime, is.... D;  

Sorry for not knowing this in advance :/

**Comment by Aussiemon** [comment]
@huzpsb Is that Call of Duty Black Ops? That's the only match I can find with that LuaJIT version and some quick googling. You might try [CoDLuaDecompiler](https://github.com/JariKCoding/CoDLuaDecompiler) instead. Even if it's not the same game, it might be the same type of script.

Good luck!

**Comment by huzpsb** [comment]
> @huzpsb Is that Call of Duty Black Ops? That's the only match I can find with that LuaJIT version and some quick googling. You might try [CoDLuaDecompiler](https://github.com/JariKCoding/CoDLuaDecompiler) instead. Even if it's not the same game, it might be the same type of script.
> 
> Good luck!

Thank you, I will check that out <3

**Comment by marsinator358** [comment]
Thanks @Aussiemon!

@huzpsb  
I've had a quick look at CoDLuaDecompiler and it seems like that the changes that are needed to support  
this bytecode version are trivial to implement. Let me know if you still want to decompile this.

**Comment by huzpsb** [comment]
> Thanks @Aussiemon!
> 
> @huzpsb I've had a quick look at CoDLuaDecompiler and it seems like that the changes that are needed to support this bytecode version are trivial to implement. Let me know if you still want to decompile this.

Thank you, I do still want to decompile this if it's trivial. <3

**Comment by marsinator358** [comment]
I've modified the decompiler and it should work now with this type of bytecode.  
I'm not sure however what the correct format of the hashes is so I've printed them as `x64:TYPE:HASH`.  
The file you have provided is also one byte too long but the decompiler will ignore this.

[luajit-decompiler-v2.zip](https://github.com/user-attachments/files/18279731/luajit-decompiler-v2.zip)

**Comment by huzpsb** [comment]
> I've modified the decompiler and it should work now with this type of bytecode. I'm not sure however what the correct format of the hashes is so I've printed them as `x64:TYPE:HASH`. The file you have provided is also one byte too long but the decompiler will ignore this.
> 
> [luajit-decompiler-v2.zip](https://github.com/user-attachments/files/18279910/luajit-decompiler-v2.zip)

Thank you! That worked

**Comment by 434432773** [comment]
> I've modified the decompiler and it should work now with this type of bytecode. I'm not sure however what the correct format of the hashes is so I've printed them as `x64:TYPE:HASH`. The file you have provided is also one byte too long but the decompiler will ignore this.
> 
> [luajit-decompiler-v2.zip](https://github.com/user-attachments/files/18279910/luajit-decompiler-v2.zip)

How to find the correct format of the hash?

**Comment by marsinator358** [comment]
> How to find the correct format of the hash?

I'm not familiar with Call of Duty so I can't answer your question. You could try asking over at [CoDLuaDecompiler](https://github.com/JariKCoding/CoDLuaDecompiler).

**Comment by 434432773** [comment]
> > 如何找到哈希的正确格式？
> 
> 我对《使命召唤》不太熟悉，所以无法回答你的问题。你可以尝试在[CoDLuaDecompiler](https://github.com/JariKCoding/CoDLuaDecompiler)上提问。

谢谢

**Comment by 434432773** [comment]
> > How to find the correct format of the hash?
> 
> I'm not familiar with Call of Duty so I can't answer your question. You could try asking over at [CoDLuaDecompiler](https://github.com/JariKCoding/CoDLuaDecompiler).

thank you

**Comment by sc1066** [comment]
Hello, author, thanks for making this tool, but can you handle Chinese GBK? I get a lot of \xB6\xE3\xB1\xDC,
GBK like \xCB\xC0\xCD\xF6漠1\xB2愦玕xCB路\xED" or name== "\xCB\xC0\xCD\xF6漠2\xB2愦玕xCB路\xED"

**Comment by 434432773** [comment]
> Hello, author, thanks for making this tool, but can you handle Chinese GBK? I get a lot of \xB6\xE3\xB1\xDC, GBK like \xCB\xC0\xCD\xF6漠1\xB2愦玕xCB路\xED" or name== "\xCB\xC0\xCD\xF6漠2\xB2愦玕xCB路\xED"

Are you reversing cod, too?
