### ISSUE TITLE
Unknown exception

### ISSUE THREAD

**Issue by 00001H** [marsinator358/luajit-decompiler-v2#7]
Whem decompiling this file, I got Unknown Exception
![image](https://github.com/marsinator358/luajit-decompiler-v2/assets/50442757/f7b8d4ac-f2a3-4073-8a9a-c465724d0bd7)

[dat.zip](https://github.com/marsinator358/luajit-decompiler-v2/files/13198322/dat.zip)

**Comment by marsinator358** [comment]
Fixed, thanks!

**Comment by 00001H** [comment]
> Fixed, thanks!

@marsinator358 Where's the fix?

**Comment by marsinator358** [comment]
Please download the executable from the latest release.

**Comment by 00001H** [comment]
Oh oh, you updated the release
I was looking for a new relese 😅

**Comment by 00001H** [comment]
@marsinator358 IT WORKED! Thank you so much. All other decompilers failed on this one.
Definitely starring this repo!
