### ISSUE TITLE
Argument variable names

### ISSUE THREAD

**Issue by gibbed** [marsinator358/luajit-decompiler-v2#9]
Currently argument variable names seem to be defined as a global pool within the file (ie: `arg_{func index}_{arg_index}`), which makes sense if they remain available across file scope.

Having them named this way means that if a function is added or removed from that file, the argument variable names end up being named differently across versions of the same script, which makes diffing different versions of the scripts a lot more annoying since every function following the function change that refers to argument variables will be "different".

Is there any way this could be addressed so that argument variable names are consistent despite function addition/removal?

**Comment by marsinator358** [comment]
Well argument names need to be unique for the entire file to avoid name conflicts with upvalues.

I'm not even sure if this is possible at all, especially once you throw in anonymous functions.  
The only way is see how this could work would be by linking the name with bytecode info, like prototype size or something.

**Comment by marsinator358** [comment]
This is now implemented as part of the `--minimize_diffs` option.
